### ISSUE TITLE
OpenTracing compatibility (question)

### ISSUE THREAD

**Issue by mareq** [openzipkin/zipkin-js#109]
[OpenTracing](http://opentracing.io/documentation/pages/supported-tracers) website proclaims that [Zipkin](http://zipkin.io/) is one of the supported implementations. However, the interface of the [tracer](https://github.com/openzipkin/zipkin-js/blob/08f86b63a5fd7ded60762f537be1845ede588ffa/packages/zipkin/src/tracer/index.js#L14) provided by `zipkin` does not seem to be any close to the official [Javascript OpenTracing API](https://github.com/opentracing/opentracing-javascript/) and it fails with the `TypeError: Uncaught error: tracer.startSpan is not a function`.

Am I missing something fundamental (quite possible), or is `openzipkin/zipkin-js` indeed incompatible with OpenTracing API? In the latter case, is there either a plan to provide compatibility with OpenTracing API (and/or willingness to accept pull requests which would provide it), or some other zipkin tracer implementation that would be compatible wityh OpenTracing API?

**Comment by adriancole** [comment]
>
> OpenTracing <http://opentracing.io/documentation/pages/supported-tracers>
> website proclaims that Zipkin <http://zipkin.io/> is one of the supported
> implementations.
>
We don't control the OpenTracing website. There are some OpenTracing
libraries that include zipkin support. Zipkin has a vast ecosystem that
predates, is larger than, and is not limited to apis that the OpenTracing
leadership decides on. Most things in zipkin are from end-users who
contribute back in ways that are native to and work best with Zipkin.

> is there either a plan to provide compatibility with OpenTracing API
> (and/or willingness to accept pull requests which would provide it), or
> some other zipkin tracer implementation that would be compatible wityh
> OpenTracing API?
>
Work here is based on volunteers. However OpenTracing is an api that
changes a lot more often than zipkin does. Arbitrarily changing the api
here would break applications with no value to them. Notably Brave (the
java tracer), has a bridge (brave-opentracing which helps people use one of
the opentracing versions when they want, but not limit Brave to decisions
made at OpenTracing, or be subject to its api drift.

I have not seen such a bridge over zipkin-js, yet. If you wanted to make
such a thing, probably best to start with a personal repository and if
others are interested in that, it could be considered further. If you do
that, you can feel free to ping me as there are a lot of gotchas to
opentracing mapping. Another approach would be to search around github. It
is likely there's another opentracing library that already has javascript
support and also a zipkin driver.

Good luck!

>

**Comment by mareq** [comment]
Thank you Adrian for fast and detailed response, it was very helpful. I guess I have a few choices: a) abandon OpenTracing idea and go the Zipkin way; b) try to build the OpenTracing bridge over zipkin-js; c) abandon Zipkin idea and use some other OpenTracin-compatible tracer (possibly Jaeger?).

My original take on it was that I am not too keen to marry any of the implementations, so the OpenTracing standard that makes it (relatively) easy to switch between them looks like the way to go. However, your saying that "OpenTracing is an api that changes a lot more often than zipkin does" may be a good reason for change in my original thinking, abandon OpenTracing and just go Zipkin. Would you please elaborate a bit more on this particular topic?

**Comment by adriancole** [comment]
>
> My original take on it was that I am not too keen to marry any of the
> implementations, so the OpenTracing standard that makes it (relatively)
> easy to switch between them looks like the way to go.
>
OpenTracing markets this ideal, but despite multiple attempts has made no
effort to introduce tests that would make interop visible, much less
possible between implementations. I'd love for this to change, but I guess
some just never switch systems?

However, your saying that "OpenTracing is an api that changes a lot more
> often than zipkin does" may be a good reason for change in my original
> thinking, abandon OpenTracing and just go Zipkin. Would you please
> elaborate a bit more on this particular topic?
>
The choice is ultimately yours, but given there are no tests in opentracing
to guarantee anything, anything working between versions is subject to the
implementor. For example, right now there's a trustworth go project which
is very stable zipkin-go-opentracing, mainly due to the culture of the
maintainer. The format and shape of the OpenTracing api are subject to
change (in some cases this may help), and they have changed repeatedly in
multiple incompatible ways over the last year+ Meanwhile, zipkin-js is
based on a stable design inspired by Finagle. We have tests here to show
literally annotations are going to get into zipkin. This is easier to
troubleshoot and it is easier to know if we break api. If you want to use
jaeger, they have a http listener (though maybe some glitches it will
likely work). There's also ways to send data to google stackdriver, too.
There is work in progress towards other clouds as well.

So, the main decision process is: are you gaining by using library X and is
that gain worth the constraints of X? up to you.. I'm biased as I prefer
the easiest way to support you, and the easiest way is zipkin-js.

**Comment by adriancole** [comment]
I think the question is answered.. in the future an openzipkin-contrib bridge from opentracing to zipkin-js would be welcome if someone wants to do it.

**Comment by haoguanjun** [comment]
https://github.com/DanielMSchmidt/zipkin-javascript-opentracing provide a wrapper for OpenTracing API.

**Comment by DanielMSchmidt** [comment]
Thank you for the alert :) Awesome to see the typescript conversion, might be a good idea to move DanielMSchmidt/zipkin-javascript-opentracing also to typescript 🤔
