### ISSUE TITLE
Add support for timeout option to HttpLogger

### ISSUE THREAD

**Issue by montmanu** [openzipkin/zipkin-js#163]
Hi! Was thinking it would be nice to be able to initialize the `HttpLogger` with arbitrary fetch options, but specifically, we'd like to be able to provide a [timeout value for `node-fetch`](https://github.com/bitinn/node-fetch#fetch-options) to abort the underlying request in the event that the Zipkin endpoint does not respond quickly enough for the application..

```javascript
// if just the timeout
let logger = new HttpLogger({ endpoint: 'http://endpoint.zipkin' , /* ... */, timeout: 2000 });

// if arbitrary
let logger = new HttpLogger({
  endpoint: 'http://endpoint.zipkin',
  /* ... */, 
  fetchOptions: { timeout: 2000 },
});
```

the supply them to the fetch client at

https://github.com/openzipkin/zipkin-js/blob/3a24206e004a774735b5a5e9ed5648e945890ac4/packages/zipkin-transport-http/src/HttpLogger.js#L38-L42

Seems straightforward, but I wanted to check with the project before starting on the implementation. Any concerns?

**Comment by adriancole** [comment]
Only q is if this will always be fetch (needs to work in browser react and
node so maybe yes is the answr?)

**Comment by montmanu** [comment]
From the looks of it, this will always be fetch

https://github.com/openzipkin/zipkin-js/blob/3a24206e004a774735b5a5e9ed5648e945890ac4/packages/zipkin-transport-http/src/HttpLogger.js#L2-L7

and since that option isn't supported by browsers (no way to abort the underlying request), it will simply be ignored when executing in that environment.

**Comment by adriancole** [comment]
Sgtm

On 22 Nov 2017 00:36, "Chris Montoro" <notifications@github.com> wrote:

From the looks of it, this will always be fetch

https://github.com/openzipkin/zipkin-js/blob/3a24206e004a774735b5a5e9ed5648
e945890ac4/packages/zipkin-transport-http/src/HttpLogger.js#L2-L7

and since that option isn't supported by browsers (no way to abort the
underlying request), it will simply be ignored when executing in that
environment.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/openzipkin/zipkin-js/issues/163#issuecomment-346084489>,
or mute the thread
