### ISSUE TITLE
How does actually zipkin works with opentracing?

### ISSUE THREAD

**Issue by jackyFeng** [openzipkin/zipkin-js#196]
Hi,

I have a silly question here instead of an issue.

We are setting up a Spring Boot project with micro-services architecture. We did some researches online and found out opentracing can be used as instrumentation tool to monitor the services' interactions together with zipkin. However, I'm a bit confused that how does opentracing works with zipkin, opentracing seems like a wrapper which allows us to choose different tracers on the go. But why would we change the tracer and choose a tracer such as zipkin in the first place without using opentracing?

The question might be silly, but trying to understand it thoroughly before we actually start the implementation.

Thanks in advance.

Jacky

**Comment by adriancole** [comment]
You raise this question on our javascript project. It seems to be about
spring-cloud-sleuth (spring boot) which configures brave-opentracing (a
bridge)

But to answer your question of why would you choose opentracing? Besides
hype? Maybe you believe one day they will support other backends which cant
be supported by data formats and are ok linking to a library that is
unstable until then? Maybe you think the will do better job at interop than
opencensus.io despite having no interop tests? This presumes you want to
switch libraries.

Anyway zipkin is implemented even by jaeger who forked us (one of the two
leads of opentracing). So anyway make your own call. I dont personally
think opentracing can deliver on its messags of vendor neutrality while
every release is incompatible and there is no transparency as to what
actually can be swapped or coexist. Mostly you can just see names listed
not how many products that say they are opentracing do what much less test
to prove it.

Anyway if you want to continue this talk please go to the
spring-cloud-sleuth gitter as this repo is javascript and we are spamming
them with something unrelated ;)

https://gitter.im/spring-cloud/spring-cloud-sleuth

On 10 Mar 2018 19:29, "jackyFeng" <notifications@github.com> wrote:

Hi,

We are setting up a Spring Boot project with micro-services architecture.
We did some researches online and found out opentracing can be used as
instrumentation tool to monitor the services' interactions together with
zipkin. However, I'm a bit confused that how does opentracing works with
zipkin, opentracing seems like a wrapper which allows us to choose
different tracers on the go. But why would we change the tracer and choose
a tracer such as zipkin in the first place without using opentracing?

The question might be silly, but trying to understand it thoroughly before
we actually start the implementation.

Thanks in advance.

Jacky

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/openzipkin/zipkin-js/issues/196>, or mute the thread

**Comment by jackyFeng** [comment]
@adriancole Thanks for the response. Will understand more about spring-cloud-sleuth.
