### ISSUE TITLE
Add axios instrumentation

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-js#348]
There are a number of broken axios instrumentation out there. Maybe it is time to have a first party one that has all the tests running etc? I'm not sure on this, so deferring to other maintainers to make the call.

@thegryfon has been working on fixups to https://github.com/geekeren/zipkin-js-instrumentation-axios 

@geekeren would you be interested in contributing yours?

**Comment by geekeren** [comment]
@adriancole Yes, I am glad to contribute my code, what can I do?

**Comment by adriancole** [comment]
@geekeren great! I think best to make a directory like we have here in a pull request. make sure you carry over your good README content and double-check the integration tests are latest.

https://github.com/openzipkin/zipkin-js/tree/master/packages

**Comment by thegryfon** [comment]
Hi @adriancole & @geekeren , so some discussion topics that I would like to propose regarding this enhancement :
1. target environment for running this instrumentation (nodejs apps,browser apps)
1. the ideal way to leverage tracer.scoped() statement in order to contain trace id context (either put it explicitly in the documentation how to, or transparently in interceptors) and the pros / cons
1. adjust the unit test, so that for each unit test sequence a new axios instance will be created, otherwise when each request creates new id,  the assertions might get mixed up with previous unit test blocks and become failed. The reason for this the : wrapAxios is called repeatedly on the same axios instance, so that actually axios interceptor has multiple instances. see for example (https://github.com/geekeren/zipkin-js-instrumentation-axios/blob/45ec6525cb98968566801a27e7fc52a33a024f51/test/integrationTest.js#L50) and ( https://github.com/geekeren/zipkin-js-instrumentation-axios/blob/45ec6525cb98968566801a27e7fc52a33a024f51/test/integrationTest.js#L91 ). Because there are multiple instance of interceptors, instrumentation.recordRequest will be called twice, and as you know each time recordRequest is called, it will create a different id. Current integration test will not fail because there are no scoped request in the test, hence traceId will always be the same. 
1. Not sure if this belongs here, because this is on zipkin-js codebase, but there are requirements to adjust the zipkin-js library so that when the target environment is a js browser application without previous trace (i.e client is the root span), it is possible to call createRootId without hacks. As of now, the HttpClient (see https://github.com/openzipkin/zipkin-js/blob/65786fd89a86c292de13a7492e8f29aec347ba18/packages/zipkin/src/instrumentation/httpClient.js#L21) will always call createChildId. This is correct if the client is a subsequent participant in tracing sequence. However if the client is the first tracing sequence, calling tracer.setId(tracer.createRootId ()) before any HttpClientInstrumentation.recordRequest will resulted in tracing sequence with missing root span.
1. if issues no.4 above is done, add debug flags in interceptor if using transparently scoped request (point no.2) is agreed upon as a good practice.

Before jumping in on the technical how to, please give inputs regarding it's 'correctness' as i'm still also trying to wrap my head around this, and whether the proposed enhancements has any risks assosiated with it. Also feel free to add if there is other enhancement that we should have included either now or later on.

as for the use cases that i can help specifically, because it is something that my team will need :
1. target environment would be browser apps
1. transparent tracer.scoped in interceptor so that existing code base is not affected, later on if needed, there is mechanism to "override" the traceid
1. debug flags in interceptor

**Comment by jcchavezs** [comment]
Ping @openzipkin/zipkin-js-champions and @uschmann in case they want to get involved on this.

**Comment by geekeren** [comment]
@thegryfon Thank you for giving me input. You're the assertions will get mixed up if I just create axios Instance in `before` not `beforeEach` lifecycle of the test, like:
```
before(() => {
    recorder = {record};
    ctxImpl = new ExplicitContext();
    tracer = new Tracer({recorder, ctxImpl});
})
```
I have spent a long time to fix the `wrapAxios` but failed, could you help me or give idea to implement the `wrapAxios` function.

**Comment by jcchavezs** [comment]
Thanks for the input @thegryfon and sorry for the late response:

> target environment for running this instrumentation (nodejs apps,browser
apps)

Tests run against both node and browser envs. Whether this is a browser
targeted instrumentation or a node one, I believe that depends on where are
you people participating on this running the instrumentation. E.g. if you
run this against node apps and it works pretty well we can say this is a
node instrumentation but encourage browser users to try it and confirm
everything works as expected. *Having a repo with example or a working
example inside the package usually does the trick.*

> the ideal way to leverage tracer.scoped() statement in order to contain
trace id context (either put it explicitly in the documentation how to, or
transparently in interceptors) and the pros / cons

Agree on this, documentation might do the trick.

> adjust the unit test, so that for each unit test sequence a new axios
instance will be created, otherwise when each request creates new id, the
assertions might get mixed up with previous unit test blocks and become
failed. The reason for this the : wrapAxios is called repeatedly on the
same axios instance, so that actually axios interceptor has multiple
instances. see for example (
https://github.com/geekeren/zipkin-js-instrumentation-axios/blob/45ec6525cb98968566801a27e7fc52a33a024f51/test/integrationTest.js#L50)
and (
https://github.com/geekeren/zipkin-js-instrumentation-axios/blob/45ec6525cb98968566801a27e7fc52a33a024f51/test/integrationTest.js#L91
).

This makes sense to me but I also see the value on reusing the same
instance tests that the span is not reused? What we maybe need is to
improve the tests so spans don't get mixed and they are all independent
(and we test that)

> Because there are multiple instance of interceptors,
instrumentation.recordRequest will be called twice, and as you know each
time recordRequest is called, it will create a different id. Current
integration test will not fail because there are no scoped request in the
test, hence traceId will always be the same.

We need definitively to fix this. Could you come up with the fix or the
failing test?

> Not sure if this belongs here, because this is on zipkin-js codebase, but
there are requirements to adjust the zipkin-js library so that when the
target environment is a js browser application without previous trace (i.e
client is the root span), it is possible to call createRootId without
hacks. As of now, the HttpClient (see
https://github.com/openzipkin/zipkin-js/blob/65786fd89a86c292de13a7492e8f29aec347ba18/packages/zipkin/src/instrumentation/httpClient.js#L21)
will always call createChildId. This is correct if the client is a
subsequent participant in tracing sequence. However if the client is the
first tracing sequence, calling tracer.setId(tracer.createRootId ()) before
any HttpClientInstrumentation.recordRequest will resulted in tracing
sequence with missing root span.

> if issues no.4 above is done, add debug flags in interceptor if using
transparently scoped request (point no.2) is agreed upon as a good practice.

I am not sure I understand the debug flags concept. You mean the debug
flags that are part of the propagation?

Ping @ghermeto

Den ons. 3. apr. 2019, 09:04 skrev Baiyuan Wang <notifications@github.com>:

**Comment by thegryfon** [comment]
@adriancole @geekeren @jcchavezs , i'm really sorry for being away so long, got so caught up in office work, and really haven't got time to look at the adjusted code. But for next month I think i can allocate a little time to look into this again.

@geekeren , i noticed that you've added zipkin-instrumentation-axios, but i also noticed that you also have patch-1 branch in your repo. Which one should i look into ? I've also noticed  some of the problem that I highlighted has been fixed in the master branch.

**Comment by geekeren** [comment]
@thegryfon The patch-1 is used to fix the issue:https://github.com/openzipkin/zipkin-js/pull/356

- pass traceId from request to response by config, traceId will change after record request
- avoid dirty axios, create an axios instance before using interceptors

**Comment by adriancole** [comment]
the aforementioned is merged, and I also sorted some build glitches. latest is zipkin-instrumentation-axiosjs@0.18.2 please proceed with new issues from here folks and many thanks!

**Comment by adriancole** [comment]
fyi I am using axios as a guinea pig for a new test infrastructure for us https://github.com/openzipkin/zipkin-js/pull/372
