### ISSUE TITLE
Some explanations of context and traceid

### ISSUE THREAD

**Issue by mikhailrojo** [openzipkin/zipkin-js#448]
Please help me with getting trace Id for my logger.
I read the exmaples. but cannot get how to get the reaceid for example to put it in my logger

do I need to get it like ``` req._trace_id ```?

is it done with 'zipkin-context-cls'? do I get it from there? if not what do I need this context for? what is stored there?
thanks

**Comment by jcchavezs** [comment]
@mikhailrojo please ask such questions over gitter instead (gitter.im/openzipkin/) which is the right channel for support.

>  I read the exmaples. but cannot get how to get the reaceid for example to put it in my logger

How do you start the trace? If you are inside that execution code, (e.g. a handler in express) you can access the context ID by doing `tracer.letId(() => console.log(tracer.id))`

> is it done with 'zipkin-context-cls'? do I get it from there? if not what do I need this context for? what is stored there?

The context is stored with cls to continue the trace inside the application without the need to pass it explicitly. This is because you can't have a global state because many request will happen concurrently.

Feel free to ask more questions over gitter.
