### ISSUE TITLE
Libraries as asap and node-fetch are used but they are not mentioned in deps

### ISSUE THREAD

**Issue by mikhailrojo** [openzipkin/zipkin-js#491]
Hi guys

I installed zipkin-instrumentation-request-promise, but got the error, that `asap` library is not installed. 

This asap library is mentioned in [devDeps section](https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin-instrumentation-request-promise/package.json#L23)
so it can not be used in production code as [import](https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin-instrumentation-request-promise/src/promise.js#L26)

the same for zipkin-transport-http [node-fetch is required](https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin-transport-http/src/HttpLogger.js#L6) but it is in [depsDev](https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin-transport-http/package.json#L20)

O_o

**Comment by jcchavezs** [comment]
Hi @mikhailrojo, thanks for opening this issue.

Regarding `asap` I think we indeed need to include it as a dependency in the package. Would you do that in a PR? cc @mkante 

The case of `node-fetch` is slightly different I think. I noticed this too when working on  https://github.com/openzipkin/zipkin-js/pull/485 but if you see `node-fetch` is a last resource as we first try to use other fetch implementations:

https://github.com/openzipkin/zipkin-js/blob/2aca37be1edca1b1e0bd62bcdb9ac20d1717c457/packages/zipkin-transport-http/src/HttpLogger.js#L2-L6

Can this be catched at compile time? If not, I think we make it clear in the readme, otherwise it sounds to me like even if there is a global fetch in place we are adding a new dependency to the user.

Any thoughts @adriancole @petermetz @anuraaga ?

**Comment by anuraaga** [comment]
How about moving it to `peerDependencies`? From what I understand of the docs, it's how to specify an optional dependency like this one 

https://docs.npmjs.com/files/package.json#peerdependencies

**Comment by jcchavezs** [comment]
Yeah I think `peerDependencies` is a good fit:

> NOTE: npm versions 1 and 2 will automatically install peerDependencies if they are not explicitly depended upon higher in the dependency tree. In the next major version of npm (npm@3), this will no longer be the case. You will receive a warning that the peerDependency is not installed instead. The behavior in npms 1 & 2 was frequently confusing and could easily put you into dependency hell, a situation that npm is designed to avoid as much as possible.

Oldest supported version of node includes npm 6: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#notable-changes-2

**Comment by jcchavezs** [comment]
Anyone?

**Comment by mikhailrojo** [comment]
I think 'node-fetch' should be included in deps, not peerDeps.
According to the code above -> it the code is executed in node(not browser) -> 'node-fetch' will be required in 100% of cases.

**Comment by jcchavezs** [comment]
Makes sense @mikhailrojo, would you be up for a PR? Do you see it related to https://github.com/openzipkin/zipkin-js/pull/497#issuecomment-623450659?

**Comment by mikhailrojo** [comment]
Hi Jose
I made a PR #505 

I tried to understand the #497  but I don't get the pain and the question.

**Comment by petermetz** [comment]
Late for the party and have no capacity for a PR right now, but just wanted to chime in with a +1 for peer dependencies. I know it can cause extra hassle in the form of one having to install an extra dependency manually, but that is usually about 10 seconds and only need to be done once.
On the other hand having it as a peer dependency allows for flexibility when it's needed and can make it easier to reduce bundle size when working with webpack for example (just my personal experiences, not an expert on webpack at all).

**Comment by mikhailrojo** [comment]
Just for the discussion: why don't we set all deps as peers? if everything is peers - the bundle size is the smallest

**Comment by jcchavezs** [comment]
> Just for the discussion: why don't we set all deps as peers? if everything is peers - the bundle size is the smallest

That is going to be a breaking change, isn't?

**Comment by mikhailrojo** [comment]
My question is mo hypothetical - just to make a point whether is is wise to add it as peers

**Comment by petermetz** [comment]
> My question is mo hypothetical - just to make a point whether is is wise to add it as peers

Personal take: there is no right answer in practice (only in theory) at the moment because both have trade-offs. 
IMHO In a perfect world you wouldn't need the concept of peer dependencies at all because bundlers would be able to tree shake and de-duplicate with 100% accuracy and side-effect free so you wouldn't even care. 
It (bundling) has gotten better over the years, but I still experience issues from time to time that makes me appreciate just how far we still need to go.
