### ISSUE TITLE
Instrumentations multiple instances

### ISSUE THREAD

**Issue by mikhailrojo** [openzipkin/zipkin-js#514]
Hi guys, why [httpClient](https://github.com/openzipkin/zipkin-js/blob/bc590b2957b4c1e0c434de3c6fb7b4feeb406f8b/packages/zipkin/src/instrumentation/httpClient.js#L17) should be created for each service separately.

Example: my MAIN app doest requests to Service1, Service2 and Service3. Why I need to create for each of them its own instrumentation, while I can do the same just once? and I can send [remoteServiceName](https://github.com/openzipkin/zipkin-js/blob/bc590b2957b4c1e0c434de3c6fb7b4feeb406f8b/packages/zipkin/src/instrumentation/httpClient.js#L20) as the 4th argument to sendRequest

**Comment by jcchavezs** [comment]
remoteServiceName is mostly a reference for the service graph. According to [API]() it is merely a "The network context of a node in the service graph". Unfortunately you can't create a span out of remoteServiceName because your main app will only know how much time it took from main app to service 1 but won't know how much time service one took to do the request processing (there is network latency and imagine there is service mesh you will find retries and scheduling).
