### ISSUE TITLE
How to know current call stack has finished

### ISSUE THREAD

**Issue by peaksnail** [openzipkin/zipkin-js#71]
hi team,I have a doubt that  the zipkin-js agent how to know current callstack has finished and then send the traced data to collector?

**Comment by adriancole** [comment]
currently, a span is marked finished when "cr" or "ss" is received

https://github.com/openzipkin/zipkin-js/blob/1b7f0664a7a4a6859de73461e89b135bf0983d0f/packages/zipkin/src/internalRepresentations.js#L137

otherwise it is flushed after 60 seconds

https://github.com/openzipkin/zipkin-js/blob/3c2b12f3875ad856d7039dc5ada0c5dfbb1ae431/packages/zipkin/src/batch-recorder.js#L13

**Comment by peaksnail** [comment]
Thanks very much. So if I develop some new plugins, I should mark 'cr' or 'ss' in span for current call stack which I should know has finished.Or I just wait for timeout. Am i right?

**Comment by adriancole** [comment]
If you are writing a plugin for an RPC framework then follow the others,
like this...

tracer.recordAnnotation(new Annotation.ServerSend());

If you are working on a non-RPC tracing, then reply back for advice
